events {
    worker_connections 1024;
}

http {
    # This line ensures the browser recognizes CSS and JS files correctly
    include /etc/nginx/mime.types;
    
    client_max_body_size 100M;
    resolver 127.0.0.11 valid=10s;

    server {
        listen 80;

        root /usr/share/nginx/html;

        location / {
            # This ensures that when you refresh a React page, it doesn't 404
            try_files $uri $uri/ /index.html;
        }

        location /api/dl {
            # Authentication gate for AI requests
            auth_request /api/auth/authorization;
            auth_request_set $authentication_uid $sent_http_uid;
            auth_request_set $authentication_city $sent_http_city;
            auth_request_set $authentication_district $sent_http_district;
            auth_request_set $authentication_state $sent_http_state;
            auth_request_set $authentication_lat $sent_http_lat;
            auth_request_set $authentication_ip $sent_http_ip;
            auth_request_set $authentication_lon $sent_http_lon;

            # Direct connection to the AI service
            proxy_pass http://dl:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X_Forwared-For $proxy_add_x_forwarded_for;

            # Passing user location data to the AI model
            proxy_set_header uid: $authentication_uid;
            proxy_set_header city: $authentication_city;
            proxy_set_header district: $authentication_district;
            proxy_set_header state: $authentication_state;
            proxy_set_header lat: $authentication_lat;
            proxy_set_header lon: $authentication_lon;
            proxy_set_header ip: $authentication_ip;
        }

        location /api/auth {
            # Direct connection to the Node.js Auth service
            proxy_pass http://auth:8080; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/auth/authorization {
            internal;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_pass http://auth:8080/api/auth/authorization;
            proxy_method GET;
            
            # ADD THESE LINES to ensure the cookie gets sent!
            proxy_pass_header Cookie;
            proxy_set_header Cookie $http_cookie;
        }
    }
}